pipeline {
    agent any

    environment {
        DOCKER_HUB_CREDENTIALS = credentials('docker-hub') // Jenkins ID of Docker Hub credentials
        DOCKER_IMAGE = 'devopsabhishekh/frontend-angular-19'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/YourGitHubUsername/frontend-angular-19.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKER_IMAGE}:latest")
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_HUB_CREDENTIALS) {
                        docker.image("${DOCKER_IMAGE}:latest").push()
                    }
                }
            }
        }
    }
}
